apiVersion: v2
name: ThrashBuddy
description: A k6-based distributed performance testing solution.
type: application
version: 2.0.0

dependencies:
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/

  - name: grafana
    version: 10.3.1
    repository: https://grafana.github.io/helm-charts
